// actors.js
// Static fallback actor list — used when the dynamic IMDB fetch fails or is unavailable.
// This file is loaded before content.js so STATIC_ACTOR_LIST is available globally.
// All URLs verified against IMDB. Add, remove, or edit entries here freely.
// Actor count: 200 (53 added March 2026 — all nm IDs verified via web search)

const STATIC_ACTOR_LIST = [
  // Timeless A-list / highly connected
  { name: "Leonardo DiCaprio", url: "https://www.imdb.com/name/nm0000138/" },
  { name: "Brad Pitt", url: "https://www.imdb.com/name/nm0000093/" },
  { name: "Tom Hanks", url: "https://www.imdb.com/name/nm0000158/" },
  { name: "Meryl Streep", url: "https://www.imdb.com/name/nm0000658/" },
  { name: "Robert De Niro", url: "https://www.imdb.com/name/nm0000134/" },
  { name: "Al Pacino", url: "https://www.imdb.com/name/nm0000199/" },
  { name: "Denzel Washington", url: "https://www.imdb.com/name/nm0000243/" },
  { name: "Anthony Hopkins", url: "https://www.imdb.com/name/nm0000164/" },
  { name: "Gary Oldman", url: "https://www.imdb.com/name/nm0000198/" },
  { name: "Daniel Day-Lewis", url: "https://www.imdb.com/name/nm0000358/" },
  { name: "Jack Nicholson", url: "https://www.imdb.com/name/nm0000197/" },
  { name: "Dustin Hoffman", url: "https://www.imdb.com/name/nm0000163/" },
  { name: "Robin Williams", url: "https://www.imdb.com/name/nm0000245/" },
  { name: "Sean Connery", url: "https://www.imdb.com/name/nm0000125/" },
  { name: "Clint Eastwood", url: "https://www.imdb.com/name/nm0000142/" },
  { name: "Marlon Brando", url: "https://www.imdb.com/name/nm0000008/" },
  { name: "Paul Newman", url: "https://www.imdb.com/name/nm0000056/" },
  { name: "Robert Redford", url: "https://www.imdb.com/name/nm0001634/" },
  { name: "Audrey Hepburn", url: "https://www.imdb.com/name/nm0000030/" },
  { name: "Bette Davis", url: "https://www.imdb.com/name/nm0000012/" },
  { name: "James Dean", url: "https://www.imdb.com/name/nm0000015/" },
  { name: "Steve McQueen", url: "https://www.imdb.com/name/nm0000537/" },
  { name: "Heath Ledger", url: "https://www.imdb.com/name/nm0005132/" },

  // Oscar heavyweights — multiple nominations
  { name: "Cate Blanchett", url: "https://www.imdb.com/name/nm0000949/" },
  { name: "Kate Winslet", url: "https://www.imdb.com/name/nm0000701/" },
  { name: "Natalie Portman", url: "https://www.imdb.com/name/nm0000204/" },
  { name: "Joaquin Phoenix", url: "https://www.imdb.com/name/nm0001618/" },
  { name: "Christian Bale", url: "https://www.imdb.com/name/nm0000288/" },
  { name: "Colin Firth", url: "https://www.imdb.com/name/nm0000147/" },
  { name: "Hugh Grant", url: "https://www.imdb.com/name/nm0000424/" },
  { name: "Rami Malek", url: "https://www.imdb.com/name/nm1785339/" },
  { name: "Christoph Waltz", url: "https://www.imdb.com/name/nm0910607/" },
  { name: "Michael Fassbender", url: "https://www.imdb.com/name/nm1055413/" },
  { name: "Jessica Chastain", url: "https://www.imdb.com/name/nm1567113/" },
  { name: "Viola Davis", url: "https://www.imdb.com/name/nm0205626/" },
  { name: "Michelle Williams", url: "https://www.imdb.com/name/nm0931329/" },
  { name: "Amy Adams", url: "https://www.imdb.com/name/nm0010736/" },
  { name: "Glenn Close", url: "https://www.imdb.com/name/nm0000335/" },
  { name: "Charlize Theron", url: "https://www.imdb.com/name/nm0000234/" },
  { name: "Jodie Foster", url: "https://www.imdb.com/name/nm0000149/" },
  { name: "Sigourney Weaver", url: "https://www.imdb.com/name/nm0000244/" },
  { name: "Tilda Swinton", url: "https://www.imdb.com/name/nm0842770/" },
  { name: "Marion Cotillard", url: "https://www.imdb.com/name/nm0182839/" },
  { name: "Penélope Cruz", url: "https://www.imdb.com/name/nm0004851/" },
  { name: "Javier Bardem", url: "https://www.imdb.com/name/nm0000849/" },
  { name: "Benicio del Toro", url: "https://www.imdb.com/name/nm0001125/" },
  { name: "Viggo Mortensen", url: "https://www.imdb.com/name/nm0001557/" },
  { name: "Julianne Moore", url: "https://www.imdb.com/name/nm0000194/" },
  { name: "Frances McDormand", url: "https://www.imdb.com/name/nm0000531/" },
  { name: "Ethan Hawke", url: "https://www.imdb.com/name/nm0000160/" },
  { name: "Jeff Bridges", url: "https://www.imdb.com/name/nm0000313/" },
  { name: "Sandra Bullock", url: "https://www.imdb.com/name/nm0000113/" },
  { name: "Halle Berry", url: "https://www.imdb.com/name/nm0000932/" },
  { name: "Mahershala Ali", url: "https://www.imdb.com/name/nm0991810/" },
  { name: "Patrick Stewart", url: "https://www.imdb.com/name/nm0001772/" },

  // 2023 Oscars (95th — films of 2022)
  { name: "Brendan Fraser", url: "https://www.imdb.com/name/nm0000409/" },
  { name: "Austin Butler", url: "https://www.imdb.com/name/nm2581521/" },
  { name: "Paul Mescal", url: "https://www.imdb.com/name/nm8958770/" },
  { name: "Colin Farrell", url: "https://www.imdb.com/name/nm0268199/" },
  { name: "Bill Nighy", url: "https://www.imdb.com/name/nm0631490/" },
  { name: "Michelle Yeoh", url: "https://www.imdb.com/name/nm0000706/" },
  { name: "Ana de Armas", url: "https://www.imdb.com/name/nm1869101/" },
  { name: "Ke Huy Quan", url: "https://www.imdb.com/name/nm0702841/" },
  { name: "Barry Keoghan", url: "https://www.imdb.com/name/nm4422686/" },
  { name: "Brendan Gleeson", url: "https://www.imdb.com/name/nm0322407/" },
  { name: "Jamie Lee Curtis", url: "https://www.imdb.com/name/nm0000130/" },
  { name: "Kerry Condon", url: "https://www.imdb.com/name/nm0174403/" },
  { name: "Angela Bassett", url: "https://www.imdb.com/name/nm0000291/" },

  // 2024 Oscars (96th — films of 2023)
  { name: "Cillian Murphy", url: "https://www.imdb.com/name/nm0614165/" },
  { name: "Bradley Cooper", url: "https://www.imdb.com/name/nm0177896/" },
  { name: "Paul Giamatti", url: "https://www.imdb.com/name/nm0316079/" },
  { name: "Colman Domingo", url: "https://www.imdb.com/name/nm0231458/" },
  { name: "Jeffrey Wright", url: "https://www.imdb.com/name/nm0942482/" },
  { name: "Emma Stone", url: "https://www.imdb.com/name/nm1297015/" },
  { name: "Lily Gladstone", url: "https://www.imdb.com/name/nm4291409/" },
  { name: "Sandra Hüller", url: "https://www.imdb.com/name/nm1197689/" },
  { name: "Carey Mulligan", url: "https://www.imdb.com/name/nm1659547/" },
  { name: "Robert Downey Jr.", url: "https://www.imdb.com/name/nm0000375/" },
  { name: "Ryan Gosling", url: "https://www.imdb.com/name/nm0331516/" },
  { name: "Mark Ruffalo", url: "https://www.imdb.com/name/nm0749263/" },
  { name: "Da'Vine Joy Randolph", url: "https://www.imdb.com/name/nm5007768/" },
  { name: "Emily Blunt", url: "https://www.imdb.com/name/nm1289434/" },
  { name: "America Ferrera", url: "https://www.imdb.com/name/nm1065229/" },

  // 2025 Oscars (97th — films of 2024)
  { name: "Adrien Brody", url: "https://www.imdb.com/name/nm0004778/" },
  { name: "Timothée Chalamet", url: "https://www.imdb.com/name/nm3154303/" },
  { name: "Ralph Fiennes", url: "https://www.imdb.com/name/nm0000146/" },
  { name: "Sebastian Stan", url: "https://www.imdb.com/name/nm1659221/" },
  { name: "Demi Moore", url: "https://www.imdb.com/name/nm0000193/" },
  { name: "Cynthia Erivo", url: "https://www.imdb.com/name/nm7248827/" },
  { name: "Mikey Madison", url: "https://www.imdb.com/name/nm5700898/" },
  { name: "Kieran Culkin", url: "https://www.imdb.com/name/nm0001085/" },
  { name: "Jeremy Strong", url: "https://www.imdb.com/name/nm0834989/" },
  { name: "Zoe Saldana", url: "https://www.imdb.com/name/nm0757855/" },
  { name: "Ariana Grande", url: "https://www.imdb.com/name/nm3812858/" },

  // Rising generation / contemporary prestige
  { name: "Florence Pugh", url: "https://www.imdb.com/name/nm6073955/" },
  { name: "Adam Driver", url: "https://www.imdb.com/name/nm3485845/" },
  { name: "Saoirse Ronan", url: "https://www.imdb.com/name/nm1519680/" },
  { name: "Andrew Scott", url: "https://www.imdb.com/name/nm0778831/" },
  { name: "Anya Taylor-Joy", url: "https://www.imdb.com/name/nm5896355/" },
  { name: "Josh O'Connor", url: "https://www.imdb.com/name/nm4853066/" },
  { name: "Andrew Garfield", url: "https://www.imdb.com/name/nm1940449/" },
  { name: "Rosamund Pike", url: "https://www.imdb.com/name/nm0683253/" },
  { name: "Margot Robbie", url: "https://www.imdb.com/name/nm3053338/" },
  { name: "Lupita Nyong'o", url: "https://www.imdb.com/name/nm2143282/" },
  { name: "Chiwetel Ejiofor", url: "https://www.imdb.com/name/nm0252230/" },
  { name: "Idris Elba", url: "https://www.imdb.com/name/nm0252961/" },
  { name: "Michael B. Jordan", url: "https://www.imdb.com/name/nm0430107/" },
  { name: "Oscar Isaac", url: "https://www.imdb.com/name/nm1209966/" },
  { name: "Pedro Pascal", url: "https://www.imdb.com/name/nm0050959/" },
  { name: "Zendaya", url: "https://www.imdb.com/name/nm3918035/" },
  { name: "Daniel Craig", url: "https://www.imdb.com/name/nm0185819/" },
  { name: "Jared Leto", url: "https://www.imdb.com/name/nm0001467/" },
  { name: "Jake Gyllenhaal", url: "https://www.imdb.com/name/nm0350453/" },
  { name: "Hugh Jackman", url: "https://www.imdb.com/name/nm0413168/" },
  { name: "Ian McKellen", url: "https://www.imdb.com/name/nm0005212/" },
  { name: "James McAvoy", url: "https://www.imdb.com/name/nm0564215/" },
  { name: "Benedict Cumberbatch", url: "https://www.imdb.com/name/nm1212722/" },
  { name: "Tom Hiddleston", url: "https://www.imdb.com/name/nm1089991/" },
  { name: "Salma Hayek", url: "https://www.imdb.com/name/nm0000161/" },
  { name: "Antonio Banderas", url: "https://www.imdb.com/name/nm0000104/" },
  { name: "Eva Green", url: "https://www.imdb.com/name/nm1200692/" },
  { name: "Rachel McAdams", url: "https://www.imdb.com/name/nm1046097/" },
  { name: "Anne Hathaway", url: "https://www.imdb.com/name/nm0004266/" },
  { name: "Jennifer Lawrence", url: "https://www.imdb.com/name/nm2225369/" },
  { name: "Scarlett Johansson", url: "https://www.imdb.com/name/nm0424060/" },
  { name: "Octavia Spencer", url: "https://www.imdb.com/name/nm0818055/" },

  // Franchise / blockbuster connectors (useful for short paths)
  { name: "Tom Cruise", url: "https://www.imdb.com/name/nm0000129/" },
  { name: "Harrison Ford", url: "https://www.imdb.com/name/nm0000148/" },
  { name: "Keanu Reeves", url: "https://www.imdb.com/name/nm0000206/" },
  { name: "Matt Damon", url: "https://www.imdb.com/name/nm0000354/" },
  { name: "Will Smith", url: "https://www.imdb.com/name/nm0000226/" },
  { name: "Samuel L. Jackson", url: "https://www.imdb.com/name/nm0000168/" },
  { name: "Morgan Freeman", url: "https://www.imdb.com/name/nm0000151/" },
  { name: "Nicolas Cage", url: "https://www.imdb.com/name/nm0000115/" },
  { name: "Johnny Depp", url: "https://www.imdb.com/name/nm0000136/" },
  { name: "Orlando Bloom", url: "https://www.imdb.com/name/nm0089217/" },
  { name: "Elijah Wood", url: "https://www.imdb.com/name/nm0000704/" },
  { name: "Daniel Radcliffe", url: "https://www.imdb.com/name/nm0705356/" },
  { name: "Emma Watson", url: "https://www.imdb.com/name/nm0914612/" },
  { name: "Alan Rickman", url: "https://www.imdb.com/name/nm0000614/" },
  { name: "Chris Evans", url: "https://www.imdb.com/name/nm0262635/" },
  { name: "Chris Hemsworth", url: "https://www.imdb.com/name/nm1165110/" },
  { name: "Dwayne Johnson", url: "https://www.imdb.com/name/nm0425005/" },
  { name: "Jackie Chan", url: "https://www.imdb.com/name/nm0000329/" },
  { name: "Adam Sandler", url: "https://www.imdb.com/name/nm0001191/" },
  { name: "Jim Carrey", url: "https://www.imdb.com/name/nm0000120/" },
  { name: "Bill Murray", url: "https://www.imdb.com/name/nm0000195/" },

  // Oscar legends & heavyweights (additions — verified March 2026)
  { name: "Nicole Kidman", url: "https://www.imdb.com/name/nm0000173/" },
  { name: "Julia Roberts", url: "https://www.imdb.com/name/nm0000210/" },
  { name: "Reese Witherspoon", url: "https://www.imdb.com/name/nm0000702/" },
  { name: "Annette Bening", url: "https://www.imdb.com/name/nm0000906/" },
  { name: "Judi Dench", url: "https://www.imdb.com/name/nm0001132/" },
  { name: "Helena Bonham Carter", url: "https://www.imdb.com/name/nm0000307/" },
  { name: "Naomi Watts", url: "https://www.imdb.com/name/nm0915208/" },
  { name: "Keira Knightley", url: "https://www.imdb.com/name/nm0461136/" },
  { name: "Kirsten Dunst", url: "https://www.imdb.com/name/nm0000379/" },
  { name: "Juliette Binoche", url: "https://www.imdb.com/name/nm0000300/" },
  { name: "Isabelle Huppert", url: "https://www.imdb.com/name/nm0001376/" },
  { name: "Eddie Murphy", url: "https://www.imdb.com/name/nm0000552/" },
  { name: "Jamie Foxx", url: "https://www.imdb.com/name/nm0004937/" },

  // Prestige & diverse talent — recent nominees/winners
  { name: "Olivia Colman", url: "https://www.imdb.com/name/nm1469236/" },
  { name: "Eddie Redmayne", url: "https://www.imdb.com/name/nm1519666/" },
  { name: "Tom Hardy", url: "https://www.imdb.com/name/nm0362766/" },
  { name: "Dev Patel", url: "https://www.imdb.com/name/nm2353862/" },
  { name: "Brie Larson", url: "https://www.imdb.com/name/nm0488953/" },
  { name: "Daniel Kaluuya", url: "https://www.imdb.com/name/nm2257207/" },
  { name: "Ariana DeBose", url: "https://www.imdb.com/name/nm3663196/" },
  { name: "Chadwick Boseman", url: "https://www.imdb.com/name/nm1569276/" },
  { name: "Troy Kotsur", url: "https://www.imdb.com/name/nm1319274/" },
  { name: "Jessie Buckley", url: "https://www.imdb.com/name/nm2976580/" },
  { name: "Steven Yeun", url: "https://www.imdb.com/name/nm3081796/" },
  { name: "John David Washington", url: "https://www.imdb.com/name/nm0913475/" },
  { name: "Riz Ahmed", url: "https://www.imdb.com/name/nm1981893/" },
  { name: "Youn Yuh-jung", url: "https://www.imdb.com/name/nm0950926/" },
  { name: "Danielle Deadwyler", url: "https://www.imdb.com/name/nm4314990/" },
  { name: "Taraji P. Henson", url: "https://www.imdb.com/name/nm0378245/" },
  { name: "Keke Palmer", url: "https://www.imdb.com/name/nm1551130/" },
  { name: "Sterling K. Brown", url: "https://www.imdb.com/name/nm1250791/" },
  { name: "Jonathan Bailey", url: "https://www.imdb.com/name/nm0047332/" },
  { name: "Awkwafina", url: "https://www.imdb.com/name/nm5377144/" },
  { name: "Hailee Steinfeld", url: "https://www.imdb.com/name/nm2794962/" },
  { name: "Naomie Harris", url: "https://www.imdb.com/name/nm0365140/" },
  { name: "Michael Shannon", url: "https://www.imdb.com/name/nm0788335/" },
  { name: "Guy Pearce", url: "https://www.imdb.com/name/nm0001602/" },
  { name: "Monica Barbaro", url: "https://www.imdb.com/name/nm4834815/" },
  { name: "Fernanda Torres", url: "https://www.imdb.com/name/nm0868639/" },
  { name: "Isabela Merced", url: "https://www.imdb.com/name/nm5097044/" },

  // Franchise / MCU / blockbuster connectors (additions)
  { name: "Tom Holland", url: "https://www.imdb.com/name/nm4043618/" },
  { name: "Daisy Ridley", url: "https://www.imdb.com/name/nm5397459/" },
  { name: "Henry Cavill", url: "https://www.imdb.com/name/nm0147147/" },
  { name: "Gal Gadot", url: "https://www.imdb.com/name/nm2933757/" },
  { name: "Jason Momoa", url: "https://www.imdb.com/name/nm0597388/" },
  { name: "Tessa Thompson", url: "https://www.imdb.com/name/nm1935086/" },
  { name: "Letitia Wright", url: "https://www.imdb.com/name/nm4004793/" },
  { name: "Anthony Mackie", url: "https://www.imdb.com/name/nm1107001/" },
  { name: "Don Cheadle", url: "https://www.imdb.com/name/nm0000332/" },
  { name: "Paul Rudd", url: "https://www.imdb.com/name/nm0748620/" },
  { name: "Jeremy Renner", url: "https://www.imdb.com/name/nm0719637/" },
  { name: "Simu Liu", url: "https://www.imdb.com/name/nm4855517/" },
  { name: "Ryan Reynolds", url: "https://www.imdb.com/name/nm0005351/" },
];
